CREATE SHEMA STUDENT;
CREATE SCHEMA ZAVRSNI;
--Kreiranje tablice korisnika i rola:
CREATE TABLE ZAVRSNI.USERS(
ID INT GENERATED ALWAYS AS IDENTITY,
USERNAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
MAIL VARCHAR(30) NOT NULL,
ADRESS VARCHAR(50) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
CITY VARCHAR(30) NOT NULL,
MOBILE VARCHAR(20) NOT NULL,
DATE_OF_BIRTH DATE,
PRIMARY KEY (ID),
FOREIGN KEY (USERNAME) REFERENCES ZAVRSNI.ROLE(USERNAME)
);

CREATE TABLE ZAVRSNI.ROLE(
USERNAME VARCHAR(30) NOT NULL,
ROLE VARCHAR(20) NOT NULL,
PRIMARY KEY (USERNAME)
);



CREATE TABLE ZAVRSNI.BOOKIE(
ID INT GENERATED ALWAYS AS IDENTITY,
NAME VARCHAR(20) NOT NULL,
BANNER VARCHAR(100) NOT NULL,
TENNIS_LINK VARCHAR(150) NOT NULL,
LOCATION_OF_FILE VARCHAR (150) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE ZAVRSNI.MATCHES(
ID INT GENERATED ALWAYS AS IDENTITY,
BOOKIE_ID_FIRST INT NOT NULL,
BOOKIE_ID_SECOND INT NOT NULL,
COUPLE VARCHAR(80) NOT NULL,
FIRST_ODD FLOAT,
SECOND_ODD FLOAT,
TIMES TIME,
DATES DATE,
RATE FLOAT,
PRIMARY KEY(ID),
FOREIGN KEY (BOOKIE_ID_FIRST) REFERENCES ZAVRSNI.BOOKIE(ID),
FOREIGN KEY (BOOKIE_ID_SECOND) REFERENCES ZAVRSNI.BOOKIE(ID)

);

CREATE TABLE ZAVRSNI.EVENT(
ID INT GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(50) NOT NULL,
RUN_TIME TIMESTAMP NOT NULL,
LINK VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE ZAVRSNI.RUNNER(
ID INT GENERATED ALWAYS AS IDENTITY,
RUNNER_NAME VARCHAR(50) NOT NULL,
JOKEY_NAME VARCHAR(50) NOT NULL,
ODD FLOAT NOT NULL,
REFRESH_TIME TIMESTAMP NOT NULL,
MAX_STAKE INT,
ID_EVENT INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_EVENT) REFERENCES ZAVRSNI.EVENT(ID)
);

INSERT INTO ZAVRSNI.EVENT (NAZIV,RUN_TIME,LINK) VALUES ('Utrka 1', '1960-01-01 23:03:20', 'http://sports.betfair.com/tennis/');

INSERT INTO ZAVRSNI.BOOKIE (NAME,BANNER,TENNIS_LINK, LOCATION_OF_FILE) VALUES ('Betfair', 'www.betfair.com', 'http://sports.betfair.com/tennis/competition?id=1554245', 'C:/Users/Programing/Proba_file/betfair_tennis.html');
INSERT INTO ZAVRSNI.BOOKIE (NAME,BANNER,TENNIS_LINK, LOCATION_OF_FILE) VALUES ('Ladbrokes', 'www.ladbrokes.com', 'http://sports.ladbrokes.com/hr-hr/Tenis-c110000009', 'C:/Users/Programing/Proba_file/ladbrokes_tennis.html');
INSERT INTO ZAVRSNI.BOOKIE (NAME,BANNER,TENNIS_LINK, LOCATION_OF_FILE) VALUES ('Bluesq', 'www.bluesq.com', 'http://www.bluesq.com/bet?action=go_coupon&coupon_id=23', 'C:/Users/Programing/Proba_file/bluesq_tennis.html');

UPDATE ZAVRSNI.BOOKIE SET TENNIS_LINK = 'http://sports.betfair.com/tennis' WHERE ID = 1;


INSERT INTO ZAVRSNI.ROLE (USERNAME, ROLE) VALUES ('Cuta', 'guest');
INSERT INTO ZAVRSNI.ROLE (USERNAME, ROLE) VALUES ('Admin', 'admin')
INSERT INTO ZAVRSNI.ROLE (USERNAME, ROLE) VALUES ('Marko', 'guest');
INSERT INTO ZAVRSNI.ROLE (USERNAME, ROLE) VALUES ('Jura', 'guest');

INSERT INTO ZAVRSNI.USERS (USERNAME, PASSWORD, MAIL, ADRESS, FIRST_NAME, LAST_NAME, CITY, MOBILE, DATE_OF_BIRTH) VALUES ('Cuta','5f4dcc3b5aa765d61d8327deb882cf99', 'jcutic@gmail.com', 
'Vidriceva 37', 'Juraj', 'Cutic', 'Zagreb', '098828343','1984-10-31');
INSERT INTO ZAVRSNI.USERS (USERNAME, PASSWORD, MAIL, ADRESS, FIRST_NAME, LAST_NAME, CITY, MOBILE, DATE_OF_BIRTH) VALUES ('Admin','5f4dcc3b5aa765d61d8327deb882cf99', 'jcutic@gmail.com', 
'Vidriceva 39', 'Juraj', 'Cutic', 'Zagreb', '098828343','1984-10-31');
INSERT INTO ZAVRSNI.USERS (USERNAME, PASSWORD, MAIL, ADRESS, FIRST_NAME, LAST_NAME, CITY, MOBILE, DATE_OF_BIRTH) VALUES ('Marko','5f4dcc3b5aa765d61d8327deb882cf99', 'jcutic@gmail.com', 
'Vidriceva 3', 'Juraj', 'Cutic', 'Zagreb', '098828343','1984-10-31');
INSERT INTO ZAVRSNI.USERS (USERNAME, PASSWORD, MAIL, ADRESS, FIRST_NAME, LAST_NAME, CITY, MOBILE, DATE_OF_BIRTH) VALUES ('Jura','5f4dcc3b5aa765d61d8327deb882cf99', 'jcutic@gmail.com', 
'Vidriceva 39', 'Juraj', 'Cutic', 'Zagreb', '098828343','1984-10-31');

--------------------------------------------------
DROP TABLE ZAVRSNI.MATCHES;
DROP TABLE ZAVRSNI.BOOKIE;
DROP TABLE ZAVRSNI.USERS;
DROP TABLE ZAVRSNI.ROLE;
TRUNCATE TABLE ZAVRSNI.MATCHES;



Delete from ZAVRSNI.USERS where USERNAME = 'rgtfrtg';

Select * from ZAVRSNI.BOOKIE;
Select * from ZAVRSNI.MATCHES; 
Select * from ZAVRSNI.USERS;
Select * from ZAVRSNI.ROLE;

Update ZAVRSNI.ROLE SET ROLE = 'ROLE_ADMIN' WHERE ROLE = 'admin';

-- Selektiranje naziva kladionica za stupce BOOKIE_ID_FIRST i BOOKIE_ID_SECOUND U SQL-u
SELECT ZAVRSNI.MATCHES.ID, ZAVRSNI.MATCHES.COUPLE, BOOKIE_FIRST.NAME, BOOKIE_SECOND.NAME
FROM ZAVRSNI.MATCHES LEFT JOIN ZAVRSNI.BOOKIE AS BOOKIE_FIRST ON ZAVRSNI.BOOKIE_FIRST.ID = ZAVRSNI.MATCHES.BOOKIE_ID_FIRST 
LEFT JOIN ZAVRSNI.BOOKIE AS BOOKIE_SECOND ON ZAVRSNI.MATCHES.BOOKIE_ID_SECOND = ZAVRSNI.BOOKIE_SECOND.ID;

--Selektiranje u HQL-u
SELECT ma.coupe, first.name, second.name, first.banner, second.banner, ma.first_odd, ma.second_odd, ma.times, ma.dates, ma.rate 
FROM Matches as ma LEFT JOIN ma.bookie_for_first as first LEFT JOIN ma.bookie_for_second as second;

